### ISSUE TITLE
Issues with `Delete Object From Json` KW

### ISSUE THREAD

**Issue by testautomation** [robotframework-thailand/robotframework-jsonlibrary#26]
I was not able to delete objects from JSON. I wanted to delete everything from **rows** in example JSON below so that I get an empy list `"rows": []`.  I have tried following jsonpaths

- `$.rows.*`   (nothing happened)
- `$..rows.*`  (nothing happened)
- `$.rows[*]`  IndexError: list assignment index out of range
- `$..rows[*]` IndexError: list assignment index out of range

```json
{
  "meta": {
    "_type": "RESULTSET",
    "_created": "2019-10-17T19:35:13.372Z",
    "_executed_aql": "SELECT e/ehr_id/value FROM EHR e"
  },
  "q": "SELECT e/ehr_id/value FROM EHR e",
  "columns": [
    {
      "name": "#0",
      "path": "/ehr_id/value"
    }
  ],
  "rows": [
    [
      "__MODIFY_EHR_ID_1__"
    ],
    [
      "__MODIFY_EHR_ID_2__"
    ],
    [
      "__MODIFY_EHR_ID_3__"
    ],
    [
      "__MODIFY_EHR_ID_4__"
    ],
    [
      "__MODIFY_EHR_ID_5__"
    ],
    [
      "__MODIFY_EHR_ID_6__"
    ],
    [
      "__MODIFY_EHR_ID_7__"
    ],
    [
      "__MODIFY_EHR_ID_8__"
    ],
    [
      "__MODIFY_EHR_ID_9__"
    ],
    [
      "__MODIFY_EHR_ID_10__"
    ]
  ]
}
```

```
Traceback (most recent call last):
  File "/.../venv/lib/python3.7/site-packages/JSONLibrary/JSONLibraryKeywords.py", line 120, in delete_object_from_json
    del(match.context.value[match.path.index])
```

Am I doing something wrong?

**Comment by elrandira** [comment]
I know this is 3years old but here's the explanation:
- if you try a Get value from Json with your 2 first jsonpath, you'll see they don't match anything. This is done by the parser used by JSONLibrary
- for the 2 last jsonpath, the parser returns the indeces of each element of rows. JSONLibrary then use these indeces to remove the element in the increasing order. The problem is that at each removal, the index increased and the number of elements in the array decreased which at some point results with the index being to high for the array size. The solution is simple: we removed the element starting with the highest index first.
