### ISSUE TITLE
Update Value To Json backwards incompatibile change

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework-thailand/robotframework-jsonlibrary#48]
Now `Update Value To Json` is **not** in place update like it was before, but exposes updated json as retuned value. Rough closed PRs reviews let me think that previous behavior was considered as bug. From my perspective it was designed correctly. Like robot collections library keyword `Set To Dictionary` is not returning new dictionary, but in-place updates given dict. 

Apart from that, such change should be at least marked as **backwards incompatible change** as has huge impact on already created test scripts.

**Comment by elrandira** [comment]
Hi @sebastianciupinski,

this "issue" was mentioned in #47. As stated in #47, the documentation of the library has always mentioned the json object should be taken from returned values of each keyword call. It is not because this bug suited you that it should be kept or mentioned as backwards incompatibility with this new release. You can check said documentation from previous releases.

you could consider the following, What is easier between :

- your case with the new release that requires to add `${json_obj}=` in front of all wrong calls 
- the case of people that always needed to call `Collections.Copy Dictionary` on their objects to avoid modifying them when they were calling the same  keyword in the previous releases?

Nevertheless, I added a comment in the "release note" visible [here](https://github.com/robotframework-thailand/robotframework-jsonlibrary/releases).

if you have several calls to update, you could consider using the replace feature of your favorite IDE. Most of them handle regex as well. Such as in notepad++ where you would be searching
`Update Value To Json\s+(\${[a-zA-Z_\s0-9]*})(.*)`

and replacing every instance with:
`\1=  Update Value To Json  \1  \2`

**Comment by sebastianciupinski** [comment]
for me it is ok now.
